#!/usr/bin/env bash
set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "${SCRIPT_DIR}/_common.sh"

main() {
  local cocoplus_dir=".cocoplus"
  local hook_log="${cocoplus_dir}/hook-log.jsonl"
  local ts session_id
  ts="$(iso_utc)"
  session_id="${COCO_SESSION_ID:-unknown}"

  if [[ ! -d "$cocoplus_dir" ]]; then
    return 0
  fi

  append_json_line "$hook_log" "{\"hook\":\"session-end\",\"session\":\"$(json_escape "$session_id")\",\"ts\":\"${ts}\"}"

  if [[ -f "${cocoplus_dir}/modes/cocometer.on" ]]; then
    local meter_file history_file started_at phase tools tokens sql writes history_line
    meter_file="${cocoplus_dir}/meter/current-session.json"
    history_file="${cocoplus_dir}/meter/history.jsonl"
    if [[ -f "$meter_file" ]]; then
      started_at="$(read_json_string "$meter_file" "started_at")"
      phase="$(read_json_string "$meter_file" "phase")"
      tools="$(read_json_number "$meter_file" "tools_called")"
      tokens="$(read_json_number "$meter_file" "tokens_consumed")"
      sql="$(read_json_number "$meter_file" "sql_statements")"
      writes="$(read_json_number "$meter_file" "writes_performed")"
      history_line="{\"session_id\":\"$(json_escape "$session_id")\",\"started_at\":\"$(json_escape "$started_at")\",\"ended_at\":\"${ts}\",\"phase\":\"$(json_escape "$phase")\",\"tools_called\":${tools:-0},\"tokens_consumed\":${tokens:-0},\"sql_statements\":${sql:-0},\"writes_performed\":${writes:-0}}"
      if ! grep -q "\"session_id\":\"$(printf '%s' "$session_id" | sed 's/[]\/$*.^|[]/\\&/g')\"" "$history_file" 2>/dev/null; then
        append_json_line "$history_file" "$history_line"
      fi
      rm -f "$meter_file"
      append_json_line "$hook_log" "{\"hook\":\"session-end\",\"action\":\"meter_finalized\",\"session\":\"$(json_escape "$session_id")\",\"ts\":\"${ts}\"}"
    fi
  fi

  if [[ -f "${cocoplus_dir}/modes/memory.on" ]]; then
    local decision_buffer decisions_file
    decision_buffer="${cocoplus_dir}/.decision-buffer"
    decisions_file="${cocoplus_dir}/memory/decisions.md"
    if [[ -f "$decision_buffer" && -s "$decision_buffer" ]]; then
      {
        printf '\n## Session %s - %s\n' "$session_id" "$ts"
        cat "$decision_buffer"
      } >> "$decisions_file" 2>/dev/null || true
      rm -f "$decision_buffer"
      append_json_line "$hook_log" "{\"hook\":\"session-end\",\"action\":\"memory_flushed\",\"session\":\"$(json_escape "$session_id")\",\"ts\":\"${ts}\"}"
    fi
  fi

  local phase modes_list decisions mode_file
  phase="$(read_json_string "${cocoplus_dir}/lifecycle/meta.json" "current_phase")"
  phase="${phase:-unknown}"
  modes_list=""
  for mode_file in "${cocoplus_dir}"/modes/*; do
    if [[ -f "$mode_file" ]]; then
      modes_list="${modes_list}- $(basename "$mode_file")"$'\n'
    fi
  done
  decisions="$(grep '^-' "${cocoplus_dir}/memory/decisions.md" 2>/dev/null | tail -3)"
  atomic_write "${cocoplus_dir}/AGENTS.md" <<EOF
# AGENTS.md — Active Personas & Session State
# Auto-generated by session-end hook. Keep ≤200 lines.

## Current Session
Ended: ${ts}
Session ID: $(json_escape "$session_id")

## CocoBrew Lifecycle
Phase: $(json_escape "$phase")

## Active Modes
${modes_list:-"- (none active)"}

## Recent Decisions
${decisions:-"(None recorded)"}
EOF
}

if ! main "$@"; then
  log_error "session-end" "failed to finalize session state"
fi

exit 0
